### ISSUE TITLE
KeyError: 'HybridTaskCascade_Cus is not in the models registry'

### ISSUE THREAD

**Issue by FabianHoerst** [boyden/NuHTC#3]
Hello,

I want to test your model, however, when I run the code, I receive the error: KeyError: 'HybridTaskCascade_Cus is not in the models registry'.

**Comment by boyden** [comment]
Hello, 

Thanks for your interest.

1.  please check if the env is correctly configured by the instructions;
2.  please check if the run directory is correct. Don't run the code in the `tools` directory but in the `NuHTC` directory;
3.  please check the `NuHTC/nuhtc/models` directory; The class `HybridTaskCascade_Cus` is implemented in `NuHTC/nuhtc/models/htc_cus.py`. Could you check if this class is correctly registered?

If you still encounter this bug, please provide more env and error information details.

**Comment by FabianHoerst** [comment]
I fixed this error by manually importing the module in the train file - However, now the I think there is an issue with the data preparation. I think the new dataset structure does not match your loading. I receive an error when loading the files: FileNotFoundError: [Errno 2] No such file or directory:`'/home/jovyan/nuhtc/PanNuke-Base/rgb/2473.png'` -> I prepared the data with your code, the files are named with the fold name in front, e.g. fold1_2473.png

**Comment by boyden** [comment]
Do you check the coco format file of PanNuke?

NuHTC
├── ...
├── coco
│   ├── PanNuke
│   │   ├── PanNuke_annt_RLE_fold1.json
│   │   ├── PanNuke_annt_RLE_fold2.json
│   │   ├── PanNuke_annt_RLE_fold3.json
├── ...

The item (image) in the file is organized as follows:
`{"fold": 1, "file_name": "fold1_2473.png", "height": 256, "width": 256, "id": 2473, "type": "Stomach", "n_objects": 67},`

**Comment by FabianHoerst** [comment]
Thanks, it is training now!
